# Generated by Django 5.1 on 2024-12-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0004_data_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='last_name',
        ),
    ]
