# Generated by Django 5.1 on 2024-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('promoters', '0006_promoter_date_of_birth'), ('promoters', '0007_promoter_date_of_death')]

    dependencies = [
        ('promoters', '0005_remove_promoter_first_name_remove_promoter_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
