# Generated by Django 5.1 on 2024-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('promoters', '0008_promoter_street_address'), ('promoters', '0009_promoter_city_promoter_country_promoter_province_and_more')]

    dependencies = [
        ('promoters', '0006_promoter_date_of_birth_squashed_0007_promoter_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='street_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
