# Generated by Django 5.1 on 2024-12-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0008_promoter_street_address_squashed_0009_promoter_city_promoter_country_promoter_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
