# Generated by Django 5.1 on 2024-12-20 03:24

from django.db import migrations


def group_address(apps, schema_editor):
    Promoter = apps.get_model("promoters", "Promoter")
    for promoter in Promoter.objects.all():
        text = ""
        if promoter.street_address:
            text += promoter.street_address + "\n"
        if promoter.city:
            text += promoter.city + "\n"
        if promoter.province:
            text += promoter.province + "\n"
        if promoter.country:
            text += promoter.country + "\n"
        if promoter.zip_code:
            text += promoter.zip_code + "\n"
        promoter.address = text
        promoter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0010_promoter_address'),
    ]

    operations = [
        # Can't undo this migration, there is no way to know which
        # lines were missing in the grouping
        migrations.RunPython(group_address),
    ]
