# Generated by Django 5.1 on 2024-12-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0011_data_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
