# Generated by Django 5.1 on 2024-12-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0012_alter_promoter_address_alter_promoter_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='province',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='zip_code',
        ),
    ]
